### ISSUE TITLE
Suggestion for Quest Book

### ISSUE THREAD

**Issue by WalaoEgg0424** [MJRLegends/Dark-Evolution-Feedback#1]
Hi MJRLegends, Im WalaoEgg0424. I would like to ask if you can add HardcoreQuestingMode to the modpack because many players like to play modpacks that have a storyline or with quests.Thats it, Thanks for reading this :D

**Comment by MJRLegends** [comment]
Yeah im in the process of building a quest book but won't be added to the mod pack for a while as it will take a lot of time to make

**Comment by WalaoEgg0424** [comment]
Ok, Thank You :D

**Comment by WalaoEgg0424** [comment]
Do you have skype? If you have skype , can you add me? My skype name is WalaoEgg0424 , THANK YOU
